// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgambgofdizxgcdjhxlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnYW1iZ29mZGl6eGdjZGpoeGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTI1MDgsImV4cCI6MjA2NzA2ODUwOH0.w31-DoHc7VFgoR1l8dGaQs4vy1TPPDEb0sQmp8yvC0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});